/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_j_principal (void);
GtkWidget* create_j_abrir (GList * tudo);
GtkWidget* create_j_save (GList * tudo);
GtkWidget* create_j_formato (GList * tudo);
GtkWidget* create_j_sobre ();
GtkWidget* create_j_erro ();
GtkWidget* create_Conv_PNM (GList * tudo);
