/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"
//#include "trabalho.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_j_principal (void)
{
  GtkWidget *j_principal;
  GtkWidget *vbox;
  GtkWidget *menu;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *menu_abrir;
  GtkWidget *menu_gravar;
  GtkWidget *menu_gravar_como;
  GtkWidget *separatormenuitem1;
  GtkWidget *separatormenuitem2;
  GtkWidget *menu_sair;
  GtkWidget *menuitem2;
  GtkWidget *menuitem2_menu;
  GtkWidget *menu_ih;
  GtkWidget *image46;
  GtkWidget *menuiv;
  GtkWidget *image47;
  GtkWidget *menurd;
  GtkWidget *image48;
  GtkWidget *menu_re;
  GtkWidget *image49;
  GtkWidget *menuitem3;
  GtkWidget *menuitem3_menu;
  GtkWidget *ver_localmente;
  GtkWidget *usar_imagemagick;
  GtkWidget *matar_imagemagick;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *sobre;
  GtkWidget *image50;
  GtkWidget *scrolled_window;
  GtkWidget *viewport1;
  GtkWidget *image_central;
  GtkWidget *hbox1;
  GtkWidget *b_iv;
  GtkWidget *image2;
  GtkWidget *b_ih;
  GtkWidget *image3;
  GtkWidget *b_rd;
  GtkWidget *image4;
  GtkWidget *b_re;
  GtkWidget *image5;
  GtkWidget *v_label1;
  GtkWidget *b_act;
  GtkWidget *image6;
  GtkWidget *b_label2;
  GtkWidget *b_to_pbm;
  GtkWidget *alignment1;
  GtkWidget *hbox2;
  GtkWidget *image7;
  GtkWidget *label3;
  GtkWidget *b_to_pgm;
  GtkWidget *alignment2;
  GtkWidget *hbox3;
  GtkWidget *image8;
  GtkWidget *label4;
  GtkWidget *b_to_ppm;
  GtkWidget *alignment3;
  GtkWidget *hbox4;
  GtkWidget *image9;
  GtkWidget *label5;
  GtkAccelGroup *accel_group;
  GtkWidget * fs_sobre;
  GtkWidget * fs_abrir;
  GtkWidget * fs_save;
  GtkWidget * fs_erro;
  GtkWidget * fs_conv;
  GtkWidget *esq;
  GtkWidget *dir;

  accel_group = gtk_accel_group_new ();

  gchar * destino = NULL;
  gchar * origem = NULL;
  gchar * temporario = g_strdup("/tmp/temporario.pnm");
  
  PNM *pnm = NULL;
  
  GList * tudo = NULL;
  
 
  j_principal = gtk_window_new (GTK_WINDOW_TOPLEVEL);
 // gtk_widget_set_size_request (j_principal, 430, 330);
  gtk_window_set_title (GTK_WINDOW (j_principal), _("Proti"));
  gtk_window_set_default_size (GTK_WINDOW (j_principal), 430, 330);
  gtk_window_set_position (GTK_WINDOW (j_principal), GTK_WIN_POS_CENTER_ALWAYS);


  tudo = g_list_insert(tudo,j_principal,j_p);
  tudo = g_list_insert(tudo,temporario,p_t);
  tudo = g_list_insert(tudo,origem,p_o);
  tudo = g_list_insert(tudo,destino,p_d);
  tudo = g_list_insert(tudo,pnm,p_pnm);
  
  g_list_nth(tudo,j_p)->data = (gpointer) j_principal;
  g_list_nth(tudo,p_t)->data = (gpointer) temporario;
  g_list_nth(tudo,p_o)->data = (gpointer) origem;
  g_list_nth(tudo,p_d)->data = (gpointer) destino;
  g_list_nth(tudo,p_pnm)->data = (gpointer) pnm;
  

  fs_sobre = create_j_sobre();
  fs_abrir = create_j_abrir(tudo);
  fs_save = create_j_save(tudo);
  fs_erro = create_j_erro();
  fs_conv = create_Conv_PNM(tudo);

  vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox);
  gtk_container_add (GTK_CONTAINER (j_principal), vbox);

  menu = gtk_menu_bar_new ();
  gtk_widget_show (menu);
  gtk_box_pack_start (GTK_BOX (vbox), menu, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_Ficheiro"));
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menu), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  menu_abrir = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (menu_abrir);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), menu_abrir);

  menu_gravar = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (menu_gravar);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), menu_gravar);

  menu_gravar_como = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (menu_gravar_como);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), menu_gravar_como);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  menu_sair = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (menu_sair);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), menu_sair);

  menuitem2 = gtk_menu_item_new_with_mnemonic (_("_Editar"));
  gtk_widget_show (menuitem2);
  gtk_container_add (GTK_CONTAINER (menu), menuitem2);

  menuitem2_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem2), menuitem2_menu);

  menu_ih = gtk_image_menu_item_new_with_mnemonic (_("Inverter _Horizontalmente"));
  gtk_widget_show (menu_ih);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), menu_ih);
  gtk_widget_add_accelerator (menu_ih, "activate", accel_group,
                              GDK_h, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image46 = create_pixmap (j_principal, "ihA16.png");
  gtk_widget_show (image46);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (menu_ih), image46);

  menuiv = gtk_image_menu_item_new_with_mnemonic (_("Inverter _Verticalmente"));
  gtk_widget_show (menuiv);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), menuiv);
  gtk_widget_add_accelerator (menuiv, "activate", accel_group,
                              GDK_v, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image47 = create_pixmap (j_principal, "ivA16.png");
  gtk_widget_show (image47);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (menuiv), image47);

  menurd = gtk_image_menu_item_new_with_mnemonic (_("Rodar para a _Direita"));
  gtk_widget_show (menurd);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), menurd);
  gtk_widget_add_accelerator (menurd, "activate", accel_group,
                              GDK_d, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image48 = create_pixmap (j_principal, "rodarDA16.png");
  gtk_widget_show (image48);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (menurd), image48);

  menu_re = gtk_image_menu_item_new_with_mnemonic (_("Rodar para a _Esquerda"));
  gtk_widget_show (menu_re);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), menu_re);
  gtk_widget_add_accelerator (menu_re, "activate", accel_group,
                              GDK_e, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image49 = create_pixmap (j_principal, "rodarEA16.png");
  gtk_widget_show (image49);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (menu_re), image49);

  menuitem3 = gtk_menu_item_new_with_mnemonic (_("_Ver"));
  gtk_widget_show (menuitem3);
  gtk_container_add (GTK_CONTAINER (menu), menuitem3);

  menuitem3_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem3), menuitem3_menu);

  ver_localmente = gtk_check_menu_item_new_with_mnemonic (_("Ver _Localmente"));
  gtk_widget_show (ver_localmente);
  gtk_container_add (GTK_CONTAINER (menuitem3_menu), ver_localmente);
  gtk_widget_add_accelerator (ver_localmente, "activate", accel_group,
                              GDK_l, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (ver_localmente), TRUE);

  separatormenuitem2 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem2);
  gtk_container_add (GTK_CONTAINER (menuitem3_menu), separatormenuitem2);
  gtk_widget_set_sensitive (separatormenuitem2, FALSE);


  usar_imagemagick = gtk_check_menu_item_new_with_mnemonic (_("_Usar ImageMagick"));
  gtk_widget_show (usar_imagemagick);
  gtk_container_add (GTK_CONTAINER (menuitem3_menu), usar_imagemagick);
  gtk_widget_add_accelerator (usar_imagemagick, "activate", accel_group,
                              GDK_u, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  matar_imagemagick = gtk_check_menu_item_new_with_mnemonic (_("_Matar ImageMagick"));
  gtk_widget_show (matar_imagemagick);
  gtk_container_add (GTK_CONTAINER (menuitem3_menu), matar_imagemagick);
  gtk_widget_add_accelerator (matar_imagemagick, "activate", accel_group,
                              GDK_m, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_Ajuda"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menu), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  sobre = gtk_image_menu_item_new_with_mnemonic (_("_Sobre"));
  gtk_widget_show (sobre);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), sobre);

  image50 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image50);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (sobre), image50);

  scrolled_window = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolled_window);
  gtk_box_pack_start (GTK_BOX (vbox), scrolled_window, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolled_window), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolled_window), viewport1);

  image_central = create_pixmap (j_principal, "eeng.png");
  gtk_widget_show (image_central);
  gtk_container_add (GTK_CONTAINER (viewport1), image_central);

  hbox1 = gtk_hbox_new (FALSE, 4);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox), hbox1, FALSE, TRUE, 2);
  gtk_widget_set_size_request (hbox1, -1, 29);

  esq = gtk_label_new ("");
  gtk_widget_show (esq);
  gtk_box_pack_start (GTK_BOX (hbox1), esq, TRUE, FALSE, 0);

  b_iv = gtk_button_new ();
  gtk_widget_show (b_iv);
  gtk_box_pack_start (GTK_BOX (hbox1), b_iv, FALSE, FALSE, 0);
  gtk_widget_set_size_request (b_iv, 36, 34);
  gtk_button_set_relief (GTK_BUTTON (b_iv), GTK_RELIEF_NONE);

  image2 = create_pixmap (j_principal, "ivA.png");
  gtk_widget_show (image2);
  gtk_container_add (GTK_CONTAINER (b_iv), image2);

  b_ih = gtk_button_new ();
  gtk_widget_show (b_ih);
  gtk_box_pack_start (GTK_BOX (hbox1), b_ih, FALSE, FALSE, 0);
  gtk_widget_set_size_request (b_ih, 36, 34);
  gtk_button_set_relief (GTK_BUTTON (b_ih), GTK_RELIEF_NONE);

  image3 = create_pixmap (j_principal, "ihA.png");
  gtk_widget_show (image3);
  gtk_container_add (GTK_CONTAINER (b_ih), image3);

  b_rd = gtk_button_new ();
  gtk_widget_show (b_rd);
  gtk_box_pack_start (GTK_BOX (hbox1), b_rd, FALSE, FALSE, 0);
  gtk_widget_set_size_request (b_rd, 36, 34);
  gtk_button_set_relief (GTK_BUTTON (b_rd), GTK_RELIEF_NONE);

  image4 = create_pixmap (j_principal, "rodarDA.png");
  gtk_widget_show (image4);
  gtk_container_add (GTK_CONTAINER (b_rd), image4);

  b_re = gtk_button_new ();
  gtk_widget_show (b_re);
  gtk_box_pack_start (GTK_BOX (hbox1), b_re, FALSE, FALSE, 0);
  gtk_widget_set_size_request (b_re, 36, 34);
  gtk_button_set_relief (GTK_BUTTON (b_re), GTK_RELIEF_NONE);

  image5 = create_pixmap (j_principal, "rodarEA.png");
  gtk_widget_show (image5);
  gtk_container_add (GTK_CONTAINER (b_re), image5);

  v_label1 = gtk_label_new ("");
  gtk_widget_show (v_label1);
  gtk_box_pack_start (GTK_BOX (hbox1), v_label1, FALSE, FALSE, 0);
  gtk_widget_set_size_request (v_label1, 10, 10);

  b_act = gtk_button_new ();
  gtk_widget_show (b_act);
  gtk_box_pack_start (GTK_BOX (hbox1), b_act, FALSE, FALSE, 0);
  gtk_widget_set_size_request (b_act, 36, 34);
  gtk_button_set_relief (GTK_BUTTON (b_act), GTK_RELIEF_NONE);

  image6 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_container_add (GTK_CONTAINER (b_act), image6);

  b_label2 = gtk_label_new ("");
  gtk_widget_show (b_label2);
  gtk_box_pack_start (GTK_BOX (hbox1), b_label2, FALSE, FALSE, 0);
  gtk_widget_set_size_request (b_label2, 10, 10);

  b_to_pbm = gtk_button_new ();
  gtk_widget_show (b_to_pbm);
  gtk_box_pack_start (GTK_BOX (hbox1), b_to_pbm, FALSE, FALSE, 0);
  gtk_widget_set_size_request (b_to_pbm, -1, 34);
  gtk_button_set_relief (GTK_BUTTON (b_to_pbm), GTK_RELIEF_NONE);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (b_to_pbm), alignment1);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox2);

  image7 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox2), image7, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("PBM"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, FALSE, FALSE, 0);

  b_to_pgm = gtk_button_new ();
  gtk_widget_show (b_to_pgm);
  gtk_box_pack_start (GTK_BOX (hbox1), b_to_pgm, FALSE, FALSE, 0);
  gtk_widget_set_size_request (b_to_pgm, -1, 34);
  gtk_button_set_relief (GTK_BUTTON (b_to_pgm), GTK_RELIEF_NONE);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (b_to_pgm), alignment2);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox3);

  image8 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox3), image8, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("PGM"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);

  b_to_ppm = gtk_button_new ();
  gtk_widget_show (b_to_ppm);
  gtk_box_pack_start (GTK_BOX (hbox1), b_to_ppm, FALSE, FALSE, 0);
  gtk_button_set_relief (GTK_BUTTON (b_to_ppm), GTK_RELIEF_NONE);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (b_to_ppm), alignment3);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox4);

  image9 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox4), image9, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("PPM"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);
  
  dir = gtk_label_new ("");
  gtk_widget_show (dir);
  gtk_box_pack_start (GTK_BOX (hbox1), dir, TRUE, FALSE, 0);

  g_signal_connect ((gpointer) menu_abrir, "activate",
                    G_CALLBACK (on_menu_abrir_activate),
                    (gpointer) tudo); 
  g_signal_connect ((gpointer) menu_gravar, "activate",
                    G_CALLBACK (on_menu_gravar_activate),
                    (gpointer) tudo);
  g_signal_connect ((gpointer) menu_gravar_como, "activate",
                    G_CALLBACK (on_menu_gravar_como_activate),
                    (gpointer) tudo);
  g_signal_connect (G_OBJECT (j_principal), "destroy",
	              G_CALLBACK (on_menu_sair_activate), NULL);
  g_signal_connect ((gpointer) menu_sair, "activate",
                    G_CALLBACK (on_menu_sair_activate),
                    (gpointer) tudo);
  g_signal_connect ((gpointer) menu_ih, "activate",
                    G_CALLBACK (on_b_ih_clicked),
                    (gpointer) tudo);
  g_signal_connect ((gpointer) menuiv, "activate",
                    G_CALLBACK (on_b_iv_clicked),
                    (gpointer) tudo);
  g_signal_connect ((gpointer) menurd, "activate",
                    G_CALLBACK (on_b_rd_clicked),
                    (gpointer) tudo);
  g_signal_connect ((gpointer) menu_re, "activate",
                    G_CALLBACK (on_b_re_clicked),
                    (gpointer) tudo);
  g_signal_connect ((gpointer) ver_localmente, "activate",
                    G_CALLBACK (on_ver_localmente_activate),
                    (gpointer) tudo);
  g_signal_connect ((gpointer) usar_imagemagick, "activate",
                    G_CALLBACK (on_usar_imagemagick_activate),
                    (gpointer) tudo);
  g_signal_connect ((gpointer) matar_imagemagick, "activate",
                    G_CALLBACK (on_matar_imagemagick_activate),
                    (gpointer) tudo);
  g_signal_connect ((gpointer) sobre, "activate",
                    G_CALLBACK (on_sobre_activate),
                    (gpointer) tudo);
  g_signal_connect ((gpointer) b_iv, "clicked",
                    G_CALLBACK (on_b_iv_clicked),
                    (gpointer) tudo);
  g_signal_connect ((gpointer) b_ih, "clicked",
                    G_CALLBACK (on_b_ih_clicked),
                    (gpointer) tudo);
  g_signal_connect ((gpointer) b_rd, "clicked",
                    G_CALLBACK (on_b_rd_clicked),
                    (gpointer) tudo);
  g_signal_connect ((gpointer) b_re, "clicked",
                    G_CALLBACK (on_b_re_clicked),
                    (gpointer) tudo);
  g_signal_connect ((gpointer) b_act, "clicked",
                    G_CALLBACK (on_b_act_clicked),
                    (gpointer) tudo);
  g_signal_connect ((gpointer) b_to_pbm, "clicked",
                    G_CALLBACK (on_b_to_pbm_clicked),
                    (gpointer) tudo);
  g_signal_connect ((gpointer) b_to_pgm, "clicked",
                    G_CALLBACK (on_b_to_pgm_clicked),
                    (gpointer) tudo);
  g_signal_connect ((gpointer) b_to_ppm, "clicked",
                    G_CALLBACK (on_b_to_ppm_clicked),
                    (gpointer) tudo);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (j_principal, j_principal, "j_principal");
  GLADE_HOOKUP_OBJECT (j_principal, vbox, "vbox");
  GLADE_HOOKUP_OBJECT (j_principal, menu, "menu");
  GLADE_HOOKUP_OBJECT (j_principal, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (j_principal, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (j_principal, menu_abrir, "menu_abrir");
  GLADE_HOOKUP_OBJECT (j_principal, menu_gravar, "menu_gravar");
  GLADE_HOOKUP_OBJECT (j_principal, menu_gravar_como, "menu_gravar_como");
  GLADE_HOOKUP_OBJECT (j_principal, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (j_principal, menu_sair, "menu_sair");
  GLADE_HOOKUP_OBJECT (j_principal, menuitem2, "menuitem2");
  GLADE_HOOKUP_OBJECT (j_principal, menuitem2_menu, "menuitem2_menu");
  GLADE_HOOKUP_OBJECT (j_principal, menu_ih, "menu_ih");
  GLADE_HOOKUP_OBJECT (j_principal, image46, "image46");
  GLADE_HOOKUP_OBJECT (j_principal, menuiv, "menuiv");
  GLADE_HOOKUP_OBJECT (j_principal, image47, "image47");
  GLADE_HOOKUP_OBJECT (j_principal, menurd, "menurd");
  GLADE_HOOKUP_OBJECT (j_principal, image48, "image48");
  GLADE_HOOKUP_OBJECT (j_principal, menu_re, "menu_re");
  GLADE_HOOKUP_OBJECT (j_principal, image49, "image49");
  GLADE_HOOKUP_OBJECT (j_principal, menuitem3, "menuitem3");
  GLADE_HOOKUP_OBJECT (j_principal, menuitem3_menu, "menuitem3_menu");
  GLADE_HOOKUP_OBJECT (j_principal, ver_localmente, "ver_localmente");
  GLADE_HOOKUP_OBJECT (j_principal, usar_imagemagick, "usar_imagemagick");
  GLADE_HOOKUP_OBJECT (j_principal, matar_imagemagick, "matar_imagemagick");
  GLADE_HOOKUP_OBJECT (j_principal, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (j_principal, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (j_principal, sobre, "sobre");
  GLADE_HOOKUP_OBJECT (j_principal, image50, "image50");
  GLADE_HOOKUP_OBJECT (j_principal, scrolled_window, "scrolled_window");
  GLADE_HOOKUP_OBJECT (j_principal, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (j_principal, image_central, "image_central");
  GLADE_HOOKUP_OBJECT (j_principal, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (j_principal, b_iv, "b_iv");
  GLADE_HOOKUP_OBJECT (j_principal, image2, "image2");
  GLADE_HOOKUP_OBJECT (j_principal, b_ih, "b_ih");
  GLADE_HOOKUP_OBJECT (j_principal, image3, "image3");
  GLADE_HOOKUP_OBJECT (j_principal, b_rd, "b_rd");
  GLADE_HOOKUP_OBJECT (j_principal, image4, "image4");
  GLADE_HOOKUP_OBJECT (j_principal, b_re, "b_re");
  GLADE_HOOKUP_OBJECT (j_principal, image5, "image5");
  GLADE_HOOKUP_OBJECT (j_principal, v_label1, "v_label1");
  GLADE_HOOKUP_OBJECT (j_principal, b_act, "b_act");
  GLADE_HOOKUP_OBJECT (j_principal, image6, "image6");
  GLADE_HOOKUP_OBJECT (j_principal, b_label2, "b_label2");
  GLADE_HOOKUP_OBJECT (j_principal, b_to_pbm, "b_to_pbm");
  GLADE_HOOKUP_OBJECT (j_principal, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (j_principal, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (j_principal, image7, "image7");
  GLADE_HOOKUP_OBJECT (j_principal, label3, "label3");
  GLADE_HOOKUP_OBJECT (j_principal, b_to_pgm, "b_to_pgm");
  GLADE_HOOKUP_OBJECT (j_principal, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (j_principal, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (j_principal, image8, "image8");
  GLADE_HOOKUP_OBJECT (j_principal, label4, "label4");
  GLADE_HOOKUP_OBJECT (j_principal, b_to_ppm, "b_to_ppm");
  GLADE_HOOKUP_OBJECT (j_principal, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (j_principal, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (j_principal, image9, "image9");
  GLADE_HOOKUP_OBJECT (j_principal, label5, "label5");
  GLADE_HOOKUP_OBJECT (j_principal, fs_sobre, "fs_sobre");
  GLADE_HOOKUP_OBJECT (j_principal, fs_erro, "fs_erro");
  GLADE_HOOKUP_OBJECT (j_principal, fs_abrir, "fs_abrir");
  GLADE_HOOKUP_OBJECT (j_principal, fs_save, "fs_save");
  GLADE_HOOKUP_OBJECT (j_principal, fs_conv, "fs_conv");

  gtk_window_add_accel_group (GTK_WINDOW (j_principal), accel_group);
  
  /*inicialmente, as seguintes funcionalidades estao desativadas*/
  gtk_widget_set_sensitive(matar_imagemagick,FALSE);
  gtk_widget_set_sensitive(menuitem2,FALSE);
  gtk_widget_set_sensitive(hbox1,FALSE);
  gtk_widget_set_sensitive(menu_gravar,FALSE);
  gtk_widget_set_sensitive(menu_gravar_como,FALSE);

  return j_principal;
}

GtkWidget*
create_Conv_PNM (GList * tudo)
{
  GtkWidget *Conv_PNM;
  GtkWidget *vbox1;
  GtkWidget *hbox2;
  GtkWidget *image1;
  GtkWidget *label3;
  GtkWidget *hseparator2;
  GtkWidget *combobox1;
  GtkWidget *hbox1;
  GtkWidget *hbuttonbox1;
  GtkWidget *cp_cancelar;
  GtkWidget *cp_ok;

  Conv_PNM = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Conv_PNM), _("Conv PNM"));
  gtk_window_set_resizable (GTK_WINDOW (Conv_PNM), FALSE);
  gtk_window_set_position (GTK_WINDOW (Conv_PNM), GTK_WIN_POS_CENTER_ALWAYS);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (Conv_PNM), vbox1);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox2, FALSE, TRUE, 0);

  image1 = gtk_image_new_from_stock ("gtk-convert", GTK_ICON_SIZE_DND);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox2), image1, FALSE, TRUE, 0);
  gtk_widget_set_size_request (image1, 60, 60);

  label3 = gtk_label_new (_("Escolha o formato para o qual \ndeseja converter o ficheiro:"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_CENTER);


  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_box_pack_start (GTK_BOX (vbox1), combobox1, FALSE, FALSE, 0);
  gtk_widget_set_size_request (combobox1, 17, 34);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("PPM"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("PGM"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("PBM"));
  
  gtk_combo_box_set_active(GTK_COMBO_BOX(combobox1),0);

  
  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator2, FALSE, FALSE, 0);
  gtk_widget_set_size_request (hseparator2, 1, 12);

  hbox1 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, TRUE, 0);
  gtk_widget_set_size_request (hbox1, -1, 38);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbuttonbox1, FALSE, FALSE, 0);
  gtk_widget_set_size_request (hbuttonbox1, -1, 38);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_SPREAD);

  cp_cancelar = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cp_cancelar);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), cp_cancelar);
  GTK_WIDGET_SET_FLAGS (cp_cancelar, GTK_CAN_DEFAULT);

  cp_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (cp_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), cp_ok);
  GTK_WIDGET_SET_FLAGS (cp_ok, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) cp_cancelar, "clicked",
                    G_CALLBACK (on_cp_cancelar_clicked),
                    (gpointer) tudo);
  g_signal_connect ((gpointer) cp_ok, "clicked",
                    G_CALLBACK (on_cp_ok_clicked),
                    (gpointer) tudo);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Conv_PNM, Conv_PNM, "Conv_PNM");
  GLADE_HOOKUP_OBJECT (Conv_PNM, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (Conv_PNM, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Conv_PNM, image1, "image1");
  GLADE_HOOKUP_OBJECT (Conv_PNM, label3, "label3");
  GLADE_HOOKUP_OBJECT (Conv_PNM, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (Conv_PNM, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (Conv_PNM, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Conv_PNM, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (Conv_PNM, cp_cancelar, "cp_cancelar");
  GLADE_HOOKUP_OBJECT (Conv_PNM, cp_ok, "cp_ok");

  return Conv_PNM;
}




GtkWidget*
create_j_abrir (GList * tudo)
{
  GtkWidget *j_abrir;
  GtkWidget *dialog_vbox1;
  GtkWidget *dialog_action_area1;
  GtkWidget *ja_cancelar;
  GtkWidget *ja_abrir;
  GtkFileFilter * filtro;
  
  filtro = gtk_file_filter_new();
  
  gtk_file_filter_set_name(filtro,"Trabalho PI");
  
  gtk_file_filter_add_mime_type(filtro, "image/jpeg");
  gtk_file_filter_add_mime_type(filtro, "image/gif");
  gtk_file_filter_add_mime_type(filtro, "text/plain");
  gtk_file_filter_add_mime_type(filtro, "image/x-portable-bitmap");
  gtk_file_filter_add_mime_type(filtro, "image/x-portable-graymap");
  gtk_file_filter_add_mime_type(filtro, "image/x-portable-pixmap");

  j_abrir = gtk_file_chooser_dialog_new ("", NULL, GTK_FILE_CHOOSER_ACTION_OPEN, NULL);
  gtk_window_set_type_hint (GTK_WINDOW (j_abrir), GDK_WINDOW_TYPE_HINT_DIALOG);

  gtk_file_chooser_add_filter(GTK_FILE_CHOOSER(j_abrir),filtro);

  dialog_vbox1 = GTK_DIALOG (j_abrir)->vbox;
  gtk_widget_show (dialog_vbox1);

  dialog_action_area1 = GTK_DIALOG (j_abrir)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  ja_cancelar = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (ja_cancelar);
  gtk_dialog_add_action_widget (GTK_DIALOG (j_abrir), ja_cancelar, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (ja_cancelar, GTK_CAN_DEFAULT);

  ja_abrir = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (ja_abrir);
  gtk_dialog_add_action_widget (GTK_DIALOG (j_abrir), ja_abrir, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (ja_abrir, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) ja_cancelar, "clicked",
                    G_CALLBACK (on_ja_cancelar_clicked),
                    (gpointer) tudo);
  g_signal_connect ((gpointer) ja_abrir, "clicked",
                    G_CALLBACK (on_ja_abrir_clicked),
                    (gpointer) tudo);
  g_signal_connect (G_OBJECT (j_abrir), "destroy",
	            G_CALLBACK (on_ja_abrir_clicked),
	            (gpointer) tudo);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (j_abrir, j_abrir, "j_abrir");
  GLADE_HOOKUP_OBJECT_NO_REF (j_abrir, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT_NO_REF (j_abrir, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (j_abrir, ja_cancelar, "ja_cancelar");
  GLADE_HOOKUP_OBJECT (j_abrir, ja_abrir, "ja_abrir");

  gtk_widget_grab_default (ja_abrir);
  
  
  return j_abrir;
}

GtkWidget*
create_j_save (GList * tudo)
{
  GtkWidget *j_save;
  GtkWidget *dialog_vbox2;
  GtkWidget *dialog_action_area2;
  GtkWidget *js_cancelar;
  GtkWidget *js_avancar;
  
  GtkWidget * fs_formato = create_j_formato(tudo);

  j_save = gtk_file_chooser_dialog_new ("", NULL, GTK_FILE_CHOOSER_ACTION_SAVE, NULL);
  gtk_window_set_type_hint (GTK_WINDOW (j_save), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox2 = GTK_DIALOG (j_save)->vbox;
  gtk_widget_show (dialog_vbox2);

  dialog_action_area2 = GTK_DIALOG (j_save)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  js_cancelar = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (js_cancelar);
  gtk_dialog_add_action_widget (GTK_DIALOG (j_save), js_cancelar, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (js_cancelar, GTK_CAN_DEFAULT);

  js_avancar = gtk_button_new_from_stock ("gtk-go-forward");
  gtk_widget_show (js_avancar);
  gtk_dialog_add_action_widget (GTK_DIALOG (j_save), js_avancar, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (js_avancar, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) js_cancelar, "clicked",
                    G_CALLBACK (on_js_cancelar_clicked),
                    (gpointer) tudo);
  g_signal_connect ((gpointer) js_avancar, "clicked",
                    G_CALLBACK (on_js_avancar_clicked),
                    (gpointer) tudo);
  g_signal_connect (G_OBJECT (j_save), "destroy",
	            G_CALLBACK (on_js_cancelar_clicked),
	            (gpointer) tudo);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (j_save, j_save, "j_save");
  GLADE_HOOKUP_OBJECT_NO_REF (j_save, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT_NO_REF (j_save, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (j_save, js_cancelar, "js_cancelar");
  GLADE_HOOKUP_OBJECT (j_save, js_avancar, "js_avancar");
  GLADE_HOOKUP_OBJECT (j_save, fs_formato, "fs_formato");

  gtk_widget_grab_default (js_avancar);
  return j_save;
}

GtkWidget*
create_j_formato (GList * tudo)
{
  GtkWidget *j_formato;
  GtkWidget *vbox1;
  GtkWidget *hbox5;
  GtkWidget *f_image;
  GtkWidget *f_label;
  GtkWidget *f_ascii;
  GSList *f_ascii_group = NULL;
  GtkWidget *f_binario;
  GtkWidget *hbox6;
  GtkWidget *f_label2;
  GtkWidget *f_cancelar;
  GtkWidget *alignment4;
  GtkWidget *hbox7;
  GtkWidget *image12;
  GtkWidget *label8;
  GtkWidget *f_gravar;
  GtkWidget *alignment5;
  GtkWidget *hbox8;
  GtkWidget *image13;
  GtkWidget *label9;

  j_formato = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (j_formato, 270, 165);
  gtk_window_set_title (GTK_WINDOW (j_formato), _("Formato..."));
  gtk_window_set_default_size (GTK_WINDOW (j_formato), 270, 165);
  gtk_window_set_resizable (GTK_WINDOW (j_formato), FALSE);
  gtk_window_set_position (GTK_WINDOW (j_formato), GTK_WIN_POS_CENTER_ALWAYS);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (j_formato), vbox1);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox5, FALSE, TRUE, 10);

  f_image = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (f_image);
  gtk_box_pack_start (GTK_BOX (hbox5), f_image, FALSE, TRUE, 5);
  gtk_widget_set_size_request (f_image, 48, 48);

  f_label = gtk_label_new (_("Escolha o formato em\n que deseja guardar o ficheiro"));
  gtk_widget_show (f_label);
  gtk_box_pack_start (GTK_BOX (hbox5), f_label, TRUE, TRUE, 3);
  gtk_label_set_justify (GTK_LABEL (f_label), GTK_JUSTIFY_CENTER);

  f_ascii = gtk_radio_button_new_with_mnemonic (NULL, _("Ascii"));
  gtk_widget_show (f_ascii);
  gtk_box_pack_start (GTK_BOX (vbox1), f_ascii, FALSE, FALSE, 3);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (f_ascii), f_ascii_group);
  f_ascii_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (f_ascii));

  f_binario = gtk_radio_button_new_with_mnemonic (NULL, _("Bin\303\241rio"));
  gtk_widget_show (f_binario);
  gtk_box_pack_start (GTK_BOX (vbox1), f_binario, FALSE, FALSE, 3);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (f_binario), f_ascii_group);
  f_ascii_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (f_binario));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (f_binario), TRUE);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox6, FALSE, TRUE, 3);

  f_label2 = gtk_label_new ("");
  gtk_widget_show (f_label2);
  gtk_box_pack_start (GTK_BOX (hbox6), f_label2, TRUE, FALSE, 0);

  f_cancelar = gtk_button_new ();
  gtk_widget_show (f_cancelar);
  gtk_box_pack_start (GTK_BOX (hbox6), f_cancelar, FALSE, FALSE, 4);
  gtk_widget_set_size_request (f_cancelar, 90, -1);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (f_cancelar), alignment4);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox7);

  image12 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox7), image12, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Cancelar"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox7), label8, FALSE, FALSE, 0);

  f_gravar = gtk_button_new ();
  gtk_widget_show (f_gravar);
  gtk_box_pack_start (GTK_BOX (hbox6), f_gravar, FALSE, FALSE, 4);
  gtk_widget_set_size_request (f_gravar, 90, -1);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (f_gravar), alignment5);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox8);

  image13 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox8), image13, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Gravar"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox8), label9, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) f_cancelar, "clicked",
                    G_CALLBACK (on_f_cancelar_clicked),
                    (gpointer) tudo);
  g_signal_connect ((gpointer) f_gravar, "clicked",
                    G_CALLBACK (on_f_gravar_clicked),
                    (gpointer) tudo);
  g_signal_connect ((gpointer) j_formato, "destroy",
                    G_CALLBACK (on_f_cancelar_clicked),
                    (gpointer) tudo);
  

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (j_formato, j_formato, "j_formato");
  GLADE_HOOKUP_OBJECT (j_formato, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (j_formato, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (j_formato, f_image, "f_image");
  GLADE_HOOKUP_OBJECT (j_formato, f_label, "f_label");
  GLADE_HOOKUP_OBJECT (j_formato, f_ascii, "f_ascii");
  GLADE_HOOKUP_OBJECT (j_formato, f_binario, "f_binario");
  GLADE_HOOKUP_OBJECT (j_formato, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (j_formato, f_label2, "f_label2");
  GLADE_HOOKUP_OBJECT (j_formato, f_cancelar, "f_cancelar");
  GLADE_HOOKUP_OBJECT (j_formato, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (j_formato, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (j_formato, image12, "image12");
  GLADE_HOOKUP_OBJECT (j_formato, label8, "label8");
  GLADE_HOOKUP_OBJECT (j_formato, f_gravar, "f_gravar");
  GLADE_HOOKUP_OBJECT (j_formato, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (j_formato, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (j_formato, image13, "image13");
  GLADE_HOOKUP_OBJECT (j_formato, label9, "label9");

  return j_formato;
}

GtkWidget*
create_j_sobre (void)
{
  GtkWidget *j_sobre;
  GtkWidget *vbox3;
  GtkWidget *hbox11;
  GtkWidget *image16;
  GtkWidget *s_label;
  GtkWidget *s_ok;
  GtkWidget *alignment7;
  GtkWidget *hbox12;
  GtkWidget *image17;
  GtkWidget *label13;

  j_sobre = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (j_sobre, 340, 150);
  gtk_window_set_title (GTK_WINDOW (j_sobre), _("j_sobre"));
  gtk_window_set_default_size (GTK_WINDOW (j_sobre), 300, 150);
  gtk_window_set_resizable (GTK_WINDOW (j_sobre), FALSE);
  gtk_window_set_position (GTK_WINDOW (j_sobre), GTK_WIN_POS_CENTER_ALWAYS);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (j_sobre), vbox3);

  hbox11 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox11, TRUE, TRUE, 0);

  image16 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_DND);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox11), image16, FALSE, TRUE, 3);

  s_label = gtk_label_new (NULL);//);
  gtk_label_set_markup (GTK_LABEL (s_label), "<big><big>Universidade Do Minho</big></big>\nTrabalho de PI\n2005-2006\n<big><big>Proti</big></big> - <big><big>Pro</big></big>cessamento de <big><big>t</big></big>exto e <big><big>i</big></big>magem\n\n<small>Realizado por:              \nSérgio Novo nº35860</small>");

  gtk_widget_show (s_label);
  gtk_box_pack_start (GTK_BOX (hbox11), s_label, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (s_label), GTK_JUSTIFY_CENTER);

  s_ok = gtk_button_new ();
  gtk_widget_show (s_ok);
  gtk_box_pack_start (GTK_BOX (vbox3), s_ok, FALSE, FALSE, 0);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (s_ok), alignment7);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox12);

  image17 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox12), image17, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Ok"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox12), label13, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) s_ok, "clicked",
                    G_CALLBACK (on_s_ok_clicked),
                    j_sobre);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (j_sobre, j_sobre, "j_sobre");
  GLADE_HOOKUP_OBJECT (j_sobre, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (j_sobre, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (j_sobre, image16, "image16");
  GLADE_HOOKUP_OBJECT (j_sobre, s_label, "s_label");
  GLADE_HOOKUP_OBJECT (j_sobre, s_ok, "s_ok");
  GLADE_HOOKUP_OBJECT (j_sobre, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (j_sobre, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (j_sobre, image17, "image17");
  GLADE_HOOKUP_OBJECT (j_sobre, label13, "label13");

  return j_sobre;
}

GtkWidget*
create_j_erro (void)
{
  GtkWidget *j_erro;
  GtkWidget *vbox2;
  GtkWidget *hbox10;
  GtkWidget *e_image;
  GtkWidget *e_label;
  GtkWidget *e_ok;
  GtkWidget *alignment6;
  GtkWidget *hbox9;
  GtkWidget *image14;
  GtkWidget *label10;

  j_erro = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (j_erro, 350, 160);
  gtk_window_set_title (GTK_WINDOW (j_erro), _("j_erro"));
  gtk_window_set_default_size (GTK_WINDOW (j_erro), 350, 160);
  gtk_window_set_position (GTK_WINDOW (j_erro), GTK_WIN_POS_CENTER_ALWAYS);
//  gtk_window_set_resizable (GTK_WINDOW (j_erro), FALSE);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (j_erro), vbox2);

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox10, TRUE, TRUE, 0);

  e_image = gtk_image_new_from_stock ("gtk-dialog-error", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (e_image);
  gtk_box_pack_start (GTK_BOX (hbox10), e_image, FALSE, TRUE, 0);
  gtk_widget_set_size_request (e_image, 60, -1);

  e_label = gtk_label_new ("");
  gtk_widget_show (e_label);
  gtk_box_pack_start (GTK_BOX (hbox10), e_label, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (e_label), GTK_JUSTIFY_CENTER);

  e_ok = gtk_button_new ();
  gtk_widget_show (e_ok);
  gtk_box_pack_start (GTK_BOX (vbox2), e_ok, FALSE, FALSE, 3);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (e_ok), alignment6);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox9);

  image14 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox9), image14, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Ok"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox9), label10, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) e_ok, "clicked",
                    G_CALLBACK (on_e_ok_clicked),
                    (gpointer) j_erro);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (j_erro, j_erro, "j_erro");
  GLADE_HOOKUP_OBJECT (j_erro, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (j_erro, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (j_erro, e_image, "e_image");
  GLADE_HOOKUP_OBJECT (j_erro, e_label, "e_label");
  GLADE_HOOKUP_OBJECT (j_erro, e_ok, "e_ok");
  GLADE_HOOKUP_OBJECT (j_erro, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (j_erro, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (j_erro, image14, "image14");
  GLADE_HOOKUP_OBJECT (j_erro, label10, "label10");

  return j_erro;
}

