	/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "trabalho.h"

int
main (int argc, char *argv[])
{

	
	switch(argc)
	{
		 case 1: {
			  GtkWidget *j_principal;
			
			  gtk_set_locale ();
			  gtk_init (&argc, &argv);

			//  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");
			  add_pixmap_directory ("/home/biosystem/Desktop/piFinal/pixmaps");
			  add_pixmap_directory ("/home/vilhena/Desktop/piFinal/pixmaps");

			  
			  j_principal = create_j_principal ();
			  gtk_widget_show (j_principal);

			  gtk_main ();
			  break;
			  }
		 		  	 
		 default: modo_texto();
		  	 break;
		 	
	}
	
  return 0;
}

